version: '3.8'

services:
  # PostgreSQL and Redis use existing external services
  
  plane-web:
    image: makeplane/plane-frontend:latest
    container_name: plane-web
    restart: unless-stopped
    environment:
      - NEXT_PUBLIC_ENABLE_OAUTH=0
      - NEXT_PUBLIC_DEPLOY_URL=https://plane.ai-servicers.com
      - NEXT_PUBLIC_API_BASE_URL=https://plane.ai-servicers.com
    depends_on:
      - plane-api
    networks:
      - traefik-proxy
      - plane-internal
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik-proxy"
      - "traefik.http.routers.plane.rule=Host(`plane.ai-servicers.com`)"
      - "traefik.http.routers.plane.entrypoints=websecure"
      - "traefik.http.routers.plane.tls=true"
      - "traefik.http.routers.plane.tls.certresolver=letsencrypt"
      - "traefik.http.services.plane.loadbalancer.server.port=3000"

  plane-api:
    image: makeplane/plane-backend:latest
    container_name: plane-api
    restart: unless-stopped
    env_file:
      - /home/administrator/projects/admin/secrets/plane.env
    command: >
      sh -c "
      python manage.py migrate &&
      python manage.py collectstatic --noinput &&
      gunicorn -w 4 -b 0.0.0.0:8000 plane.wsgi:application
      "
    volumes:
      - plane-uploads:/code/uploads
    extra_hosts:
      - "linuxserver.lan:172.22.0.1"
    networks:
      - plane-internal
      - traefik-proxy

  plane-worker:
    image: makeplane/plane-backend:latest
    container_name: plane-worker
    restart: unless-stopped
    env_file:
      - /home/administrator/projects/admin/secrets/plane.env
    command: celery -A plane worker -l info
    volumes:
      - plane-uploads:/code/uploads
    extra_hosts:
      - "linuxserver.lan:172.22.0.1"
    depends_on:
      - plane-api
    networks:
      - plane-internal

  plane-beat:
    image: makeplane/plane-backend:latest
    container_name: plane-beat
    restart: unless-stopped
    env_file:
      - /home/administrator/projects/admin/secrets/plane.env
    command: celery -A plane beat -l info
    extra_hosts:
      - "linuxserver.lan:172.22.0.1"
    depends_on:
      - plane-api
    networks:
      - plane-internal

volumes:
  plane-uploads:

networks:
  traefik-proxy:
    external: true
  plane-internal:
    driver: bridge